# proto-file: oak/proto/manager.proto
# proto-message: oak.ApplicationConfiguration

node_configs {
  name: "frontend-config"
  wasm_config {
    module_bytes: "<bytes>"
  }
}
node_configs {
  name: "backend-config"
  wasm_config {
    module_bytes: "<bytes>"
  }
}
node_configs {
  name: "log"
  log_config {}
}
node_configs {
  name: "storage"
  storage_config {
    address: "localhost:7867"
  }
}
grpc_port: 8080
initial_node_config_name: "app"
initial_entrypoint_name: "oak_main"
