presubmit: style build-and-test

build-and-test:
    # For some reason, proto/... is broken.
    bazel test  -c opt //...:all -- -//third_party/... -//proto/...

style:
    # For some reason, proto/... is broken.
    bazel build --keep_going --config=rustfmt --config=clippy "$@" //...:all -- -//third_party/... -//proto/...
