#
# Copyright 2025 The Project Oak Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

workspace(name = "oak_private_memory")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

local_repository(
    name = "oak",
    path = "..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@oak//bazel:repositories.bzl", "oak_toolchain_repositories")

oak_toolchain_repositories()

load("@oak//bazel/rust:defs.bzl", "setup_rust_dependencies")

setup_rust_dependencies()

load("@oak//bazel/crates:patched_crates.bzl", "load_patched_crates")

load_patched_crates()

load("@oak//bazel/crates:repositories.bzl", "create_oak_crate_repositories")
load("@rules_rust//crate_universe:defs.bzl", "crate")

create_oak_crate_repositories(
    extra_packages = {
        "aes-gcm-siv": crate.spec(version = "0.11.1"),
        "codespan-reporting": crate.spec(version = "0.12.0"),
        "cxx": crate.spec(version = "1.0.157"),
        "cxx-build": crate.spec(version = "1.0.157"),
        "foldhash": crate.spec(version = "0.1.5"),
        "proc-macro2": crate.spec(version = "1.0.95"),
        "rand": crate.spec(version = "0.9.1"),
        "rustversion": crate.spec(version = "1.0.20"),
        "serde-aux": crate.spec(version = "4.6.0"),
    },
)

load("@oak//bazel/crates:crates.bzl", "load_oak_crate_repositories")

load_oak_crate_repositories()

http_archive(
    # Has to be `cxx.rs` as `cxx` hardcodes this name.
    name = "cxx.rs",
    patch_cmds = ["sed -i 's/@crates\\.io/@oak_crates_index/g' BUILD.bazel"],
    sha256 = "91d29f7ddd9eedda896cfde88c9c96d796e217061195843511f403090d2248ca",
    strip_prefix = "cxx-1.0.157",
    url = "https://github.com/dtolnay/cxx/archive/refs/tags/1.0.157.tar.gz",
)
