#!/bin/sh

# rules_rust doesn't create these files when they are missing. But just having
# an empty file present is enough to get things going.

touch Cargo-test.bazel.lock
touch Cargo_no_std-test.bazel.lock
touch Cargo_no_std_no_avx-test.bazel.lock
touch cargo-bazel-test-lock.json
touch cargo-no-std-no-avx-test-bazel-lock.json
touch cargo-no-std-test-bazel-lock.json
