workspace(name = "test_workspace")

local_repository(
    # Give it a different name to ensure that this doesn't break any
    # dependencies resolutions.
    name = "oak2",
    path = "../..",
)

load("@oak2//bazel/llvm:deps.bzl", "load_llvm_repositories")

load_llvm_repositories(oak_repo_name = "oak2")

load("@oak2//bazel/llvm:defs.bzl", "setup_llvm_toolchains")

setup_llvm_toolchains()

load("@oak2//bazel/llvm:reg.bzl", "register_llvm_toolchains")

register_llvm_toolchains()

load("@oak2//bazel/rust:deps.bzl", "load_rust_repositories")

load_rust_repositories()

load("@oak2//bazel/rust:defs.bzl", "setup_rust_dependencies")

setup_rust_dependencies(oak_repo_name = "oak2")

load("@oak2//bazel/crates:repositories.bzl", "create_oak_crate_repositories")

create_oak_crate_repositories(
    cargo_lockfile = "//:Cargo-test.bazel.lock",
    lockfile = "//:cargo-bazel-test-lock.json",
    no_std_cargo_lockfile = "//:Cargo_no_std-test.bazel.lock",
    no_std_lockfile = "//:cargo-no-std-test-bazel-lock.json",
    no_std_no_avx_cargo_lockfile = "//:Cargo_no_std_no_avx-test.bazel.lock",
    no_std_no_avx_lockfile = "//:cargo-no-std-no-avx-test-bazel-lock.json",
)

load("@oak2//bazel/crates:crates.bzl", "load_oak_crate_repositories")

load_oak_crate_repositories()
