#!/bin/sh

docker build --tag=oak .
docker run \
  --interactive \
  --tty \
  --volume=bazel-cache:/root/.cache/bazel \
  --volume=$PWD:/opt/my-project \
  --workdir=/opt/my-project \
  --publish=8888:8888 \
  oak:latest \
  bazel build --config=enc-sim //oak/server:oak

#bazel run //oak/client -- --server_address=127.0.0.1:8888
#grpc_cli ls 127.0.0.1:8888
