#!/bin/sh

docker run --interactive \
  --tty \
  --volume bazel-cache:/root/.cache/bazel \
  --volume $PWD:/opt/my-project \
  --volume $PWD/../wac:/opt/wac \
  --workdir /opt/my-project \
  gcr.io/asylo-framework/asylo \
  bash
