#!/bin/sh
set -e
set -x

./build_server_docker

docker run \
  --interactive \
  --tty \
  --volume=bazel-cache:/root/.cache/bazel \
  --volume=$PWD:/opt/my-project \
  --workdir=/opt/my-project \
  --publish=8888:8888 \
  --publish=30000:30000 \
  oak:latest \
  ./bazel-bin/oak/server/oak

#bazel run //oak/client -- --server_address=127.0.0.1:8888
#grpc_cli ls 127.0.0.1:8888
