#!/bin/sh
set -e
set -x

#bazel build //examples/go/hello_world

#--business_logic=$PWD/bazel-bin/examples/go/hello_world/js_wasm_pure_stripped/hello_world \

# To install rust:
#
# curl https://sh.rustup.rs -sSf | sh
# rustup toolchain install nightly
# rustup target add wasm32-unknown-unknown --toolchain nightly

cargo +nightly build --release --target=wasm32-unknown-unknown --manifest-path=rust/oak/examples/hello_world/Cargo.toml
cargo +nightly build --release --target=wasm32-unknown-unknown --manifest-path=rust/oak/examples/machine_learning/Cargo.toml
cargo +nightly build --release --target=wasm32-unknown-unknown --manifest-path=rust/oak/examples/millionaires/Cargo.toml

bazel run //oak/client -- \
  --server_address=127.0.0.1:8888 \
  --business_logic=$PWD/rust/oak/examples/millionaires/target/wasm32-unknown-unknown/release/millionaires.wasm \
  --expression='add 11 22'
