#!/bin/sh
set -e

#bazel build //examples/go/hello_world

#--business_logic=$PWD/bazel-bin/examples/go/hello_world/js_wasm_pure_stripped/hello_world \

# To install rust:
#
# curl https://sh.rustup.rs -sSf | sh
# rustup toolchain install nightly
# rustup target add wasm32-unknown-unknown --toolchain nightly

cargo +nightly build --target=wasm32-unknown-unknown --manifest-path=examples/rust/hello_world/Cargo.toml

bazel run //oak/client -- \
  --server_address=127.0.0.1:8888 \
  --business_logic=$PWD/examples/rust/hello_world/target/wasm32-unknown-unknown/debug/hello_world.wasm \
  --expression='add 11 22'
