#!/bin/sh
set -e
set -x

#bazel build //examples/go/hello_world

#--business_logic=$PWD/bazel-bin/examples/go/hello_world/js_wasm_pure_stripped/hello_world \

# To install rust:
#
# curl https://sh.rustup.rs -sSf | sh
# rustup toolchain install nightly
# rustup target add wasm32-unknown-unknown --toolchain nightly

#readonly EXAMPLE_NAME=hello_world
#readonly EXAMPLE_NAME=machine_learning
readonly EXAMPLE_NAME=millionaires

cargo +nightly build --release --target=wasm32-unknown-unknown --manifest-path=rust/oak/examples/$EXAMPLE_NAME/Cargo.toml

bazel run //oak/client -- \
  --server_address=127.0.0.1:8888 \
  --business_logic=$PWD/rust/oak/examples/$EXAMPLE_NAME/target/wasm32-unknown-unknown/release/$EXAMPLE_NAME.wasm \
  --expression='add 11 22'
