#!/usr/bin/env bash

# Thin shell script invoked as a cargo runner to run the compiled efi firmware
# in QEMU. Detects if kvm is supported, and sets qemu flags based on that.
# Instead of this single runner script it would be preferable to use a different
# runner based on whether the kvm feature is set. However, cargo does not
# currently allow this. Ref: https://github.com/rust-lang/cargo/issues/8170

readonly TARGET=$1

qemu_flags=(
  '-nodefaults'
  '-nographic'
  '-no-reboot'
  '-serial' 'file:/dev/stdout'
  '-serial' 'stdio'
  '-machine' 'q35'
  '-device' 'isa-debug-exit,iobase=0xf4,iosize=0x04'
)

# Use kvm if supported, as it is required for certain features.
if [[ -e "/dev/kvm" ]]; then
  qemu_flags+=(
    '-enable-kvm'
    '-cpu' 'IvyBridge-IBRS,enforce'
  )
fi

qemu-system-x86_64 "${qemu_flags[@]}" -kernel "${TARGET}"

# Massive hack: if we return 33 ((0x10 << 1) | 1) call it a success.
# The return val 0x10 is defined as QemuExitCode::Success in main.rs.
status=$?
if test $status -eq 33; then 
  exit 0
fi
exit $status
