// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oak_abi/proto/identity.proto

#include "oak_abi/proto/identity.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace oak {
namespace identity {
class SignedChallengeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SignedChallenge> _instance;
} _SignedChallenge_default_instance_;
}  // namespace identity
}  // namespace oak
static void InitDefaultsscc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::oak::identity::_SignedChallenge_default_instance_;
    new (ptr) ::oak::identity::SignedChallenge();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::oak::identity::SignedChallenge::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_oak_5fabi_2fproto_2fidentity_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_oak_5fabi_2fproto_2fidentity_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_oak_5fabi_2fproto_2fidentity_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_oak_5fabi_2fproto_2fidentity_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oak::identity::SignedChallenge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::oak::identity::SignedChallenge, signed_hash_),
  PROTOBUF_FIELD_OFFSET(::oak::identity::SignedChallenge, public_key_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::oak::identity::SignedChallenge)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::oak::identity::_SignedChallenge_default_instance_),
};

const char descriptor_table_protodef_oak_5fabi_2fproto_2fidentity_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034oak_abi/proto/identity.proto\022\014oak.iden"
  "tity\032\033google/protobuf/empty.proto\":\n\017Sig"
  "nedChallenge\022\023\n\013signed_hash\030\001 \001(\014\022\022\n\npub"
  "lic_key\030\002 \001(\014b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_sccs[1] = {
  &scc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_once;
static bool descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto = {
  &descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_initialized, descriptor_table_protodef_oak_5fabi_2fproto_2fidentity_2eproto, "oak_abi/proto/identity.proto", 141,
  &descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_once, descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_sccs, descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_oak_5fabi_2fproto_2fidentity_2eproto::offsets,
  file_level_metadata_oak_5fabi_2fproto_2fidentity_2eproto, 1, file_level_enum_descriptors_oak_5fabi_2fproto_2fidentity_2eproto, file_level_service_descriptors_oak_5fabi_2fproto_2fidentity_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_oak_5fabi_2fproto_2fidentity_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_oak_5fabi_2fproto_2fidentity_2eproto), true);
namespace oak {
namespace identity {

// ===================================================================

void SignedChallenge::InitAsDefaultInstance() {
}
class SignedChallenge::_Internal {
 public:
};

SignedChallenge::SignedChallenge()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:oak.identity.SignedChallenge)
}
SignedChallenge::SignedChallenge(const SignedChallenge& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  signed_hash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_signed_hash().empty()) {
    signed_hash_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.signed_hash_);
  }
  public_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_public_key().empty()) {
    public_key_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.public_key_);
  }
  // @@protoc_insertion_point(copy_constructor:oak.identity.SignedChallenge)
}

void SignedChallenge::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto.base);
  signed_hash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  public_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SignedChallenge::~SignedChallenge() {
  // @@protoc_insertion_point(destructor:oak.identity.SignedChallenge)
  SharedDtor();
}

void SignedChallenge::SharedDtor() {
  signed_hash_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  public_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SignedChallenge::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SignedChallenge& SignedChallenge::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SignedChallenge_oak_5fabi_2fproto_2fidentity_2eproto.base);
  return *internal_default_instance();
}


void SignedChallenge::Clear() {
// @@protoc_insertion_point(message_clear_start:oak.identity.SignedChallenge)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  signed_hash_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  public_key_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* SignedChallenge::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes signed_hash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_signed_hash();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes public_key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_public_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SignedChallenge::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oak.identity.SignedChallenge)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes signed_hash = 1;
  if (this->signed_hash().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_signed_hash(), target);
  }

  // bytes public_key = 2;
  if (this->public_key().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_public_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oak.identity.SignedChallenge)
  return target;
}

size_t SignedChallenge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oak.identity.SignedChallenge)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes signed_hash = 1;
  if (this->signed_hash().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_signed_hash());
  }

  // bytes public_key = 2;
  if (this->public_key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_public_key());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SignedChallenge::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:oak.identity.SignedChallenge)
  GOOGLE_DCHECK_NE(&from, this);
  const SignedChallenge* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SignedChallenge>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:oak.identity.SignedChallenge)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:oak.identity.SignedChallenge)
    MergeFrom(*source);
  }
}

void SignedChallenge::MergeFrom(const SignedChallenge& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:oak.identity.SignedChallenge)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.signed_hash().size() > 0) {

    signed_hash_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.signed_hash_);
  }
  if (from.public_key().size() > 0) {

    public_key_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.public_key_);
  }
}

void SignedChallenge::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:oak.identity.SignedChallenge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SignedChallenge::CopyFrom(const SignedChallenge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oak.identity.SignedChallenge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignedChallenge::IsInitialized() const {
  return true;
}

void SignedChallenge::InternalSwap(SignedChallenge* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  signed_hash_.Swap(&other->signed_hash_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  public_key_.Swap(&other->public_key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata SignedChallenge::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace identity
}  // namespace oak
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::oak::identity::SignedChallenge* Arena::CreateMaybeMessage< ::oak::identity::SignedChallenge >(Arena* arena) {
  return Arena::CreateInternal< ::oak::identity::SignedChallenge >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
