node_configs {
  name: "app"
  wasm_config {
    module_bytes: "<bytes>"
  }
}
node_configs {
  name: "translator"
  wasm_config {
    module_bytes: "<bytes>"
  }
}
node_configs {
  name: "log"
  log_config {}
}
node_configs {
  name: "storage"
  storage_config {
    address: "localhost:7867"
  }
}
node_configs {
  name: "translator-grpc"
  grpc_client_config {
    address: "localhost:7770"
  }
}
grpc_port: 8080
initial_node_config_name: "app"
initial_entrypoint_name: "oak_main"
