//
// Copyright 2026 The Project Oak Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//! Integration tests that verify that the keys generated by the Oak Restricted
//! Kernel orchestrator (application signing key, application encryption key,
//! and derived sealing key) are erased from memory once handed to the enclave
//! application.

use googletest::prelude::*;
use oak_file_utils::data_path;
use oak_test_utils::{QemuBuilder, QemuDump};
use sha2::{Digest, Sha256};

const READY_MARKER: &str = "test application ready for memory dump";

/// Derives the fixed, predictable P-256 ECDSA application signing key used by
/// the test-only orchestrator.
fn orchestrator_application_signing_key() -> [u8; 32] {
    const ORCHESTRATOR_APPLICATION_SIGNING_KEY_SEED: &[u8] =
        b"oak orchestrator application signing fixed test key seed v1";
    let mut hasher = Sha256::new();
    hasher.update(ORCHESTRATOR_APPLICATION_SIGNING_KEY_SEED);
    let mut key = [0u8; 32];
    hasher.finalize_into((&mut key).into());
    key
}

/// Derives the fixed, predictable X25519 application encryption private key
/// used by the test-only orchestrator.
fn orchestrator_application_encryption_key() -> [u8; 32] {
    const ORCHESTRATOR_APPLICATION_ENCRYPTION_KEY_SEED: &[u8] =
        b"oak orchestrator application encryption fixed test key seed v1";
    let mut hasher = Sha256::new();
    hasher.update(ORCHESTRATOR_APPLICATION_ENCRYPTION_KEY_SEED);
    let mut seed = [0u8; 32];
    hasher.finalize_into((&mut seed).into());
    let (encryption_key, _) = oak_crypto::encryption_key::derive_encryption_key_pair(&seed);
    let serialized = encryption_key.serialize();
    let mut key = [0u8; 32];
    key.copy_from_slice(&serialized);
    key
}

/// Derives the fixed, predictable derived sealing key used by the test-only
/// orchestrator.
fn orchestrator_application_derived_key() -> [u8; 32] {
    const ORCHESTRATOR_APPLICATION_DERIVED_KEY_SEED: &[u8] =
        b"oak orchestrator application derived fixed test key seed v1";
    let mut hasher = Sha256::new();
    hasher.update(ORCHESTRATOR_APPLICATION_DERIVED_KEY_SEED);
    let mut key = [0u8; 32];
    hasher.finalize_into((&mut key).into());
    key
}

fn boot_and_dump() -> anyhow::Result<QemuDump> {
    let kernel = data_path(
        "oak_restricted_kernel_wrapper/oak_restricted_kernel_wrapper_virtio_console_channel_bin",
    );
    let bios = data_path("stage0_bin/stage0_bin");
    let initrd = data_path("enclave_apps/oak_orchestrator/insecure_oak_orchestrator_fixed_key");
    let app_binary = data_path("oak_restricted_kernel/testing/enclave_app");

    QemuBuilder::new(kernel)
        .bios(bios)
        .initrd(initrd)
        .app_binary(app_binary)
        .boot_and_dump(READY_MARKER)
}

/// Verifies that the application signing private key generated by the
/// orchestrator is erased from guest physical memory.
#[googletest::test]
fn assert_application_signing_key_erased() {
    let dump = boot_and_dump().unwrap();
    let key = orchestrator_application_signing_key();

    // Sanity check: the key is non-trivial
    assert_that!(key, not(eq([0u8; 32])));

    let hits = dump.core.find_in_guest_memory(&key);
    let leaked: Vec<String> = hits.iter().map(|a| format!("0x{a:x}")).collect();
    assert_that!(leaked, is_empty());
}

/// Verifies that the application encryption private key generated by the
/// orchestrator is erased from guest physical memory.
#[googletest::test]
fn assert_application_encryption_key_erased() {
    let dump = boot_and_dump().unwrap();
    let key = orchestrator_application_encryption_key();

    // Sanity check: the key is non-trivial
    assert_that!(key, not(eq([0u8; 32])));

    let hits = dump.core.find_in_guest_memory(&key);
    let leaked: Vec<String> = hits.iter().map(|a| format!("0x{a:x}")).collect();
    assert_that!(leaked, is_empty());
}

/// Verifies that the application derived sealing key generated by the
/// orchestrator is erased from guest physical memory.
#[googletest::test]
fn assert_application_derived_key_erased() {
    let dump = boot_and_dump().unwrap();
    let key = orchestrator_application_derived_key();

    // Sanity check: the key is non-trivial
    assert_that!(key, not(eq([0u8; 32])));

    let hits = dump.core.find_in_guest_memory(&key);
    let leaked: Vec<String> = hits.iter().map(|a| format!("0x{a:x}")).collect();
    assert_that!(leaked, is_empty());
}

/// Sanity test: verifies that search in guest memory works as expected by
/// finding the ready marker string that the test app emitted.
#[googletest::test]
fn sanity_finds_marker_in_guest_memory() {
    let dump = boot_and_dump().unwrap();

    let hits = dump.core.find_in_guest_memory(READY_MARKER.as_bytes());
    assert_that!(hits, not(is_empty()));
}
