#!/usr/bin/env bash
set -o xtrace

curl \
  --include \
  --fail-early \
  --http2 \
  --http2-prior-knowledge \
  --request POST \
  --data '{"lat":1,"lon":2}' \
  --silent \
  --output /dev/null \
  --write-out '%{http_code}\n%{content_type}\n' \
  localhost:8080/invoke
