#!/bin/sh
set -e
set -x

cargo build --release --target=wasm32-unknown-unknown --manifest-path=examples/machine_learning/Cargo.toml
bazel run //examples/machine_learning/client -- \
  --module=$PWD/examples/target/wasm32-unknown-unknown/release/machine_learning.wasm
