# hadolint ignore=DL3007
FROM oak_docker:latest

# This runs in the context of each example, e.g. the 'current folder'
# is examples/{current_example}, so we just need the config.bin file from the bin folder
COPY bin/config.bin .
