#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
readonly GLOBAL_ROOT_DIR="${SCRIPTS_DIR}/../../.."
readonly GLOBAL_SCRIPTS_DIR="${GLOBAL_ROOT_DIR}/scripts/"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

"${SCRIPTS_DIR}/undeploy" || true

gcloud container clusters get-credentials aggregator
kubectl create secret generic tls-private-key \
  --from-file="${GLOBAL_ROOT_DIR}/examples/certs/docker/docker.key" \
  --from-file="${GLOBAL_ROOT_DIR}/examples/certs/docker/docker.pem" \
  --from-file="${GLOBAL_ROOT_DIR}/examples/certs/docker/ca.pem"
kubectl apply --filename="${GLOBAL_ROOT_DIR}/examples/aggregator/gcp/pod.yaml"
