#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

"${SCRIPTS_DIR}/undeploy" || true

gcloud container clusters get-credentials aggregator
kubectl apply --filename=examples/aggregator/gcp/pod.yaml
