#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

"${GLOBAL_SCRIPTS_DIR}/build_example" -e aggregator

# Run the application client.
"./bazel-client-bin/examples/aggregator/client/cpp/client" --ca_cert_path=./examples/certs/gcp/ca.pem "${@}"
