#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

exec cargo run --release --manifest-path=examples/aggregator/backend/Cargo.toml -- \
  --grpc-tls-private-key="${GLOBAL_SCRIPTS_DIR}/../examples/certs/local/local.key" \
  --grpc-tls-certificate="${GLOBAL_SCRIPTS_DIR}/../examples/certs/local/local.pem"
