#!/usr/bin/env bash

readonly GLOBAL_SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")/../../../scripts/"
readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "${GLOBAL_SCRIPTS_DIR}/common"

"${GLOBAL_SCRIPTS_DIR}/build_server" -s base

readonly APPLICATION="${PWD}/bazel-client-bin/examples/aggregator/config/config.bin"
exec ./bazel-bin/oak/server/loader/oak_runner \
  --application="${APPLICATION}" \
  --ca_cert="${SCRIPTS_DIR}/../examples/certs/docker/ca.pem" \
  --cert_chain="${SCRIPTS_DIR}/../examples/certs/docker/local.pem" \
  --private_key="${SCRIPTS_DIR}/../examples/certs/docker/local.key"
