#!/usr/bin/env bash

# A simple script to create a tarball of an example OCI Runtime Bundle (https://github.com/opencontainers/runtime-spec/blob/4e3b9264a330d094b0386c3703c5f379119711e8/bundle.md)
# that can be executed on Oak Containers. Used for manual testing during
# development. Down the line we probably want to replace this.

readonly CONTAINER_IMAGE='oak_container_example'
set -e
rm --recursive --force ./target
mkdir --parents ./target

cargo build \
    --package='oak_containers_hello_world_trusted_app' \
    --target='x86_64-unknown-linux-musl' \
    -Zunstable-options \
    --out-dir='./target/'

docker build --tag="${CONTAINER_IMAGE}" .

../scripts/export_container_bundle \
    -c "${CONTAINER_IMAGE}" \
    -o './target/oak_container_example_oci_filesystem_bundle.tar'
