FROM trzeci/emscripten:sdk-incoming-64bit
MAINTAINER Joel Martin <github@martintribe.org>

RUN dpkg --add-architecture i386 && \
    apt-get -y update && \
    apt-get -y install git-core cmake g++ \
        lib32gcc-4.9-dev libSDL2-dev:i386 libedit-dev:i386

RUN git clone https://github.com/WebAssembly/binaryen/ && \
    cd binaryen && \
    cmake . && make && \
    make install

RUN git clone --recursive https://github.com/WebAssembly/wabt/ && \
    cd wabt && \
    make gcc-release && \
    make install-gcc-release && \
    cp /src/wabt/bin/* /usr/local/bin/

# Cache emscripten port of SDL2
RUN echo 'BINARYEN_ROOT="/usr/local"' >> /root/.emscripten && \
    echo 'RELOCATABLE=""' >> /root/.emscripten && \
    rm -r /root/.emscripten_cache* && \
    echo "int main() {}" > /tmp/nop.c && \
    emcc -s WASM=1 -s SIDE_MODULE=1 -O2 -s USE_SDL=2 /tmp/nop.c -o /tmp/nop.wasm && \
    emcc --show-ports && \
    rm /tmp/nop*

# To make sure emcc registers a timestamp difference properly do this
# as a separate run command
RUN touch /root/.emscripten_sanity



