FROM debian:jessie
MAINTAINER Joel Martin <github@martintribe.org>

# Based on https://github.com/asRIA/emscripten-docker by kontakt@trzeci.eu

RUN dpkg --add-architecture i386 && \
    apt-get -y update && \
    apt-get -y install \
	wget git-core ca-certificates build-essential python \
        g++ lib32gcc-4.9-dev \
        libSDL2-dev:i386 libedit-dev:i386 freeglut3-dev:i386

# emsdk manifest with kanaka specific entries
ADD emsdk_manifest.json ./

RUN rm /bin/sh && ln -s /bin/bash /bin/sh \
	\
&&	wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh -q \
&&	mkdir /opt/cmake \
&&	printf "y\nn\n" | sh cmake-3.6.3-Linux-x86_64.sh --prefix=/opt/cmake \
&&		rm -fr cmake*.sh /opt/cmake/doc \
&&		rm -fr /opt/cmake/bin/cmake-gui \
&&		rm -fr /opt/cmake/bin/ccmake \
&&		rm -fr /opt/cmake/bin/cpack \
&&	ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake \
	\
&&	git clone --depth 1 https://github.com/juj/emsdk.git emsdk_portable \
&&	cd emsdk_portable \
&&      cp ../emsdk_manifest.json ./ \
&&	rm -fr .git \
&&	rm -fr bin \
&&	./emsdk install --build=MinSizeRel sdk-kanaka-64bit \
&&	./emsdk activate sdk-kanaka-64bit \
	\
&&	find . -name "CMakeFiles" -type d -prune -exec rm -fr {} \; \
&&	find . -name "*.o" -exec rm {} \; \
&&	find . -name "*.a" -exec rm {} \; \
&&	emscripten_version=$(find clang/*/src/emscripten-version.txt) \
&&	mv $emscripten_version emscripten-version.txt \
&&	rm -rf clang/*/src \
&&	mkdir -p $(echo "$(dirname "$emscripten_version")") \
&&	mv emscripten-version.txt $emscripten_version \
&&	rm -rf emscripten/*/.git \
&&	rm -rf zips \
&&	rm -rf emscripten/*/tests \
&&	rm -rf /emsdk_manifest.json \
	\
&&	for prog in asm2wasm s2wasm wasm-as wasm-dis wasm-merge wasm-opt wasm-shell ; do \
	ln -sf /emsdk_portable/binaryen/master_64bit_binaryen/bin/$prog /usr/local/bin; done \
	\
&&	ln -sf /emsdk_portable/node/8.0.0-nightly20170427892ce06dbd_64bit/bin/$prog /usr/local/bin \
	\
&&	for prog in em++ em-config emar emcc emconfigure emmake emranlib emrun emscons emcmake; do \
	ln -sf /emsdk_portable/emscripten/kanaka/$prog /usr/local/bin; done \
        \
&&      ln -sf /emsdk_portable/node/8.0.0-nightly20170427892ce06dbd_64bit/bin/node /usr/local/bin/node \
	\
&&	EMSCRIPTEN=/emsdk_portable/emscripten/kanaka \
	\
&&	emcc --version \
	\
&&	mkdir -p /tmp/emscripten_test && cd /tmp/emscripten_test \
&&	printf '#include <iostream>\nint main(){std::cout<<"HELLO"<<std::endl;return 0;}' > test.cpp \
&&	em++ -O2 test.cpp -o test.js && node test.js \
&&	em++ test.cpp -o test.js && node test.js \
	\
&&	$EMSCRIPTEN/embuilder.py build ALL \
	\
&&	cd / \
&&	rm -fr /tmp/emscripten_test \
	\
&&	apt-get -y clean \
&&	apt-get -y autoclean \
&&	apt-get -y autoremove \
	\
&&	rm -rf /var/cache/debconf/*-old \
&&	cp -R /usr/share/locale/en\@* /tmp/ && rm -rf /usr/share/locale/* && mv /tmp/en\@* /usr/share/locale/ \
&&	echo "BUILD FINISHED"

# TODO: move up
RUN apt-get -y install libsdl2-image-2.0-0:i386 libsdl2-image-dev:i386

# SETUP SDK
ENV EMSCRIPTEN=/emsdk_portable/emscripten/kanaka
WORKDIR /src
