//
// Copyright 2021 The Project Oak Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//! Test utilities to help with unit testing of Oak Functions code.

pub static MOCK_LOOKUP_DATA_PATH: Lazy<PathBuf> =
    Lazy::new(|| workspace_path(&["oak_functions_launcher", "mock_lookup_data"]));

pub static OAK_RESTRICTED_KERNEL_WRAPPER_BIN: Lazy<PathBuf> = Lazy::new(|| {
    workspace_path(&[
        "oak_restricted_kernel_wrapper",
        "target",
        "x86_64-unknown-none",
        "release",
        "oak_restricted_kernel_wrapper_bin",
    ])
});

use std::{collections::HashMap, future::Future, io::Write, path::PathBuf, pin::Pin, task::Poll};

use command_group::stdlib::CommandGroup;
use oak_client::verifier::InsecureAttestationVerifier;
use oak_functions_abi::Response;
use oak_functions_client::OakFunctionsClient;
use once_cell::sync::Lazy;
use prost::Message;
use tokio::{sync::oneshot, task::JoinHandle};
use ubyte::ByteUnit;

// Creates a path relative to the workspace root.
pub fn workspace_path(relative_path: &[&str]) -> PathBuf {
    [&[env!("WORKSPACE_ROOT")], relative_path].concat().iter().collect()
}

/// Serializes the provided map as a contiguous buffer of length-delimited
/// protobuf messages of type [`Entry`](https://github.com/project-oak/oak/blob/main/proto/oak_functions/lookup_data.proto).
pub fn serialize_entries(entries: HashMap<Vec<u8>, Vec<u8>>) -> Vec<u8> {
    let mut buf = Vec::new();
    for (key, value) in entries.into_iter() {
        let entry_proto = oak_proto_rust::oak::functions::lookup_data::Entry { key, value };
        entry_proto
            .encode_length_delimited(&mut buf)
            .expect("couldn't encode entry as length delimited");
    }
    buf
}

// Create lookup data entries mapping keys to themselves which, when chunked,
// will be chunked to chunk_count chunks of max_chunk_size.
pub fn create_test_lookup_data(
    max_chunk_size: ByteUnit,
    chunk_count: u32,
) -> HashMap<Vec<u8>, Vec<u8>> {
    let mut entries = std::collections::HashMap::new();

    let entry_size = ByteUnit::Byte(10);
    // This has to be consistent with the overhead set in chunking up lookup data.
    let entry_overhead = ByteUnit::Byte(10);
    let chunk_overhead = ByteUnit::Byte(50);
    let max_entries_by_chunk =
        ((max_chunk_size - chunk_overhead) / (entry_size + entry_overhead)).as_u64() as u32;

    for i in 0..(max_entries_by_chunk * chunk_count) {
        // Pad to 5 bytes to have 10 byte entries
        let n = format!("{:05}", i).into_bytes();
        entries.insert(n.clone(), n);
    }
    entries
}

pub fn write_to_temp_file(content: &[u8]) -> tempfile::NamedTempFile {
    let mut file = tempfile::NamedTempFile::new().expect("couldn't create temp file");
    file.write_all(content).expect("couldn't write content to temp file");
    file
}

pub fn free_port() -> u16 {
    port_check::free_local_port().expect("couldn't pick free local port")
}

/// Wrapper around a termination signal [`oneshot::Sender`] and the
/// [`JoinHandle`] of the associated background task, created by [`background`].
pub struct Background<T> {
    term_tx: oneshot::Sender<()>,
    join_handle: JoinHandle<T>,
}

impl<T> Background<T> {
    /// Sends the termination signal to the background task and awaits for it to
    /// gracefully terminate.
    ///
    /// This does not guarantee that the background task terminates (e.g. if it
    /// ignores the termination signal), it requires the cooperation of the
    /// task in order to work correctly.
    pub async fn terminate_and_join(self) -> T {
        self.term_tx.send(()).expect("couldn't send signal on termination channel");
        self.join_handle.await.expect("couldn' wait for background task to terminate")
    }
}

/// Executes the provided closure passing to it a [`Term`] instance signalling
/// when to terminate, and spawns the resulting [`Future`] in the background,
/// returning a [`Background`] instance.
pub fn background<Out, F>(f: F) -> Background<Out::Output>
where
    Out: Future + Send + 'static,
    Out::Output: Send + 'static,
    F: FnOnce(Term) -> Out,
{
    let (term_tx, term_rx) = oneshot::channel::<()>();
    let term = Term { rx: term_rx };
    let join_handle = tokio::spawn(f(term));
    Background { term_tx, join_handle }
}

/// Returns the path of the Wasm module generated by the crate identified by the
/// given package name.
pub fn rust_crate_wasm_out_path(crate_name: &str) -> String {
    format!("{}target/wasm32-unknown-unknown/release/{crate_name}.wasm", env!("WORKSPACE_ROOT"),)
}

pub fn rust_crate_enclave_out_path(crate_name: &str) -> String {
    format!(
        "{}enclave_apps/target/x86_64-unknown-none/release/{crate_name}",
        env!("WORKSPACE_ROOT"),
    )
}

/// A wrapper around a termination signal [`oneshot::Receiver`].
///
/// This type manually implements [`Future`] in order to be able to be passed to
/// a closure as part of [`background`].
pub struct Term {
    rx: oneshot::Receiver<()>,
}

impl Future for Term {
    type Output = ();
    fn poll(self: Pin<&mut Self>, c: &mut std::task::Context) -> Poll<()> {
        let rx = &mut self.get_mut().rx;
        tokio::pin!(rx);
        match rx.poll(c) {
            Poll::Ready(v) => {
                v.unwrap();
                Poll::Ready(())
            }
            Poll::Pending => Poll::Pending,
        }
    }
}

pub async fn make_request(port: u16, request_body: &[u8]) -> Vec<u8> {
    let uri = format!("http://localhost:{port}/");

    // Create client
    let mut client = OakFunctionsClient::new(&uri, &InsecureAttestationVerifier {})
        .await
        .expect("couldn't create client");

    client.invoke(request_body).await.expect("error response")
}

// Assert that string value of the body of the given response matches the
// expected string.
pub fn assert_response_body(response: Response, expected: &str) {
    let body = response.body().unwrap();
    assert_eq!(
        std::str::from_utf8(body).expect("couldn't convert response body from utf8"),
        expected
    )
}

/// Runs the specified example as a background task. Returns a reference to the
/// running server and the port on which the server is listening.
pub fn run_oak_functions_containers_example_in_background(
    wasm_path: &str,
    lookup_data_path: &str,
    communication_channel: &str,
) -> (BackgroundHandle, u16) {
    eprintln!("using Wasm module {}", wasm_path);

    let port = portpicker::pick_unused_port().expect("failed to pick a port");
    eprintln!("using port {}", port);

    let child = std::process::Command::new("just")
        .args(vec![
            "run_oak_functions_containers_launcher",
            wasm_path,
            &format!("{}", port),
            lookup_data_path,
            communication_channel,
            &format!("{}", nix::unistd::gettid()),
        ])
        .group_spawn()
        .expect("didn't start oak functions containers launcher");

    (BackgroundHandle(child), port)
}

/// A wrapper around a child process that kills it when its dropped.
pub struct BackgroundHandle(pub command_group::GroupChild);

impl std::ops::Drop for BackgroundHandle {
    fn drop(&mut self) {
        self.0.kill().expect("Couldn't kill command group")
    }
}

/// Runs the specified example as a background task. Returns a reference to the
/// running server and the port on which the server is listening.
pub fn run_oak_functions_example_in_background(
    wasm_path: &str,
    lookup_data_path: &str,
) -> (BackgroundHandle, u16) {
    eprintln!("using Wasm module {}", wasm_path);

    let port = portpicker::pick_unused_port().expect("failed to pick a port");
    eprintln!("using port {}", port);

    let child = std::process::Command::new("just")
        .args(vec!["run_oak_functions_launcher", wasm_path, &format!("{}", port), lookup_data_path])
        .group_spawn()
        .expect("didn't start oak functions containers launcher");

    (BackgroundHandle(child), port)
}

pub fn run_java_client(addr: &str) -> std::io::Result<std::process::Output> {
    std::process::Command::new("just")
        .arg("run-java-functions-client")
        .arg(addr)
        .current_dir(workspace_path(&[]))
        .output()
}

pub fn run_cc_client(addr: &str, request: &str) -> std::io::Result<std::process::Output> {
    std::process::Command::new("just")
        .arg("run-cc-functions-client")
        .arg(addr)
        .arg(request)
        .current_dir(workspace_path(&[]))
        .output()
}

/// Whether to skip the test. For instance, GitHub Actions does not support KVM,
/// so we cannot run tests that require nested virtualization.
pub fn skip_test() -> bool {
    std::env::var("OAK_KVM_TESTS").unwrap_or_default().to_lowercase() == "skip"
}
