(function() {var implementors = {};
implementors["oak"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"oak/io/struct.Channel.html\" title=\"struct oak::io::Channel\">Channel</a>",synthetic:false,types:["oak::io::Channel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"oak/proto/code/enum.Code.html\" title=\"enum oak::proto::code::Code\">Code</a>",synthetic:false,types:["oak::proto::code::Code"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"oak/proto/oak_api/enum.OakStatus.html\" title=\"enum oak::proto::oak_api::OakStatus\">OakStatus</a>",synthetic:false,types:["oak::proto::oak_api::OakStatus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"oak/proto/oak_api/enum.ChannelReadStatus.html\" title=\"enum oak::proto::oak_api::ChannelReadStatus\">ChannelReadStatus</a>",synthetic:false,types:["oak::proto::oak_api::ChannelReadStatus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"oak/struct.ReadHandle.html\" title=\"struct oak::ReadHandle\">ReadHandle</a>",synthetic:false,types:["oak::ReadHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"oak/struct.WriteHandle.html\" title=\"struct oak::WriteHandle\">WriteHandle</a>",synthetic:false,types:["oak::WriteHandle"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
