#!/usr/bin/env bash

for file in "$@"; do
    buildozer "add licenses notice" "$file:__pkg__"
    readonly result=$?
    # exit code 3 = success, no changes made. Annoying.
    if [[ "$result" != "3" && "$result" != "0" ]]; then
        echo "ERROR: Failed to add license to $file ($result)"
        exit 1
    fi
done
