#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"
readonly BINARY_PATH="/opt/my-project/bazel-out/k8-dbg/bin/oak/server/asylo/oak_host_loader"

# find core file
readonly COREFILE="$(find . -name "core" -type f | head -n 1)" 

if [[ -f "$COREFILE" ]]; then 
  gdb -c "$COREFILE" "$BINARY_PATH" \
  -ex "set pagination 0" \
  -ex "load oak_enclave_debug" \
  -ex "thread apply all bt"
fi