#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

CONFIG='clang'

while getopts "at" opt; do
    case "$opt" in
    a)
        CONFIG="asan"
        ;;
    t)
        CONFIG="tsan"
        ;;
    *)
        exit 1
        ;;
    esac
done

bazel_build_flags+=(
    "--config=${CONFIG}"
)

# Use a different output_base so that we don't lose incremental state.
# See https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_base.
bazel --output_base="$CACHE_DIR/$CONFIG" build "${bazel_build_flags[@]}" //oak/server/dev:dev_oak_runner //oak/server/storage:storage_server
