#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

COMPILATION_MODE='fastbuild'

bazel_build_flags+=(
  '--fat_apk_cpu=x86_64'
  '--linkopt=-llog'
  '--symlink_prefix=bazel-client-android-'
  "--compilation_mode=$COMPILATION_MODE"
)

# Use a different output_base so that we don't lose incremental state.
# See https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_base.
# TODO: Remove `--fat_apk_cpu=x86_64`, when Asylo will support ARM architecture.
# https://github.com/google/asylo/issues/55
bazel --output_base="$CACHE_DIR/client-android" build "${bazel_build_flags[@]}" //examples/hello_world/client/android:client_app
