#!/bin/bash
#
# Check that artifacts can be reproducibly built, both when re-building them on the same machine
# over time, but also when built on different machines (e.g. locally vs on GCP).
#
# This script should be re-run every time any of these artifacts changes, and should be checked in
# so that we can enforce in CI that the hashes are indeed consistent.

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# List of artifacts that are expected to be reproducibly built.
readonly REPRODUCIBLE_ARTIFACTS=(
  ./target/wasm32-unknown-unknown/release/*.wasm
  ./bazel-clang-bin/oak/server/loader/oak_runner
  ./target/debug/oak_loader
)

# Index file containing hashes of the reproducible artifacts, alongside their file names.
readonly REPRODUCIBILITY_INDEX='./reproducibility_index'

# Generate the index file by computing the hashes of the artifacts.
# The index file must be checked in, and
sha256sum "${REPRODUCIBLE_ARTIFACTS[@]}" > "${REPRODUCIBILITY_INDEX}"
