#!/usr/bin/env bash

set -o errexit
set -o xtrace

readonly CACHE_DIR='bazel-cache'

bazel \
    --output_base="$CACHE_DIR/dev" \
    build \
    --symlink_prefix='dev-' \
    --config=clang \
    //oak/server/dev:oak
