#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

readonly BUILD_SCRIPT=$1
readonly OUTPUT_PATH=$2

readonly BUILD_COMMAND="./scripts/docker_run ${BUILD_SCRIPT}"
eval "${BUILD_COMMAND}"
readonly BINARY_SHA_256_HASH=$(sha256sum "${OUTPUT_PATH}" | cut -d " " -f 1)

readonly COMMIT_HASH=$(git rev-parse --verify HEAD)

mkdir -p "./provenance"
mkdir -p "./provenance/${BINARY_SHA_256_HASH}"

cat << EOF >> "./provenance/${BINARY_SHA_256_HASH}/${COMMIT_HASH}.toml"
repo = "https://github.com/project-oak/oak"
commit_hash = "$(git rev-parse --verify HEAD)"
builder_image = "${DOCKER_IMAGE_REPO_DIGEST}"
command = ["${BUILD_COMMAND}"]
output_path = "${OUTPUT_PATH}"
expected_binary_sha256_hash = "${BINARY_SHA_256_HASH}"
EOF

