#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

bazel_build_flags+=(
    '--config=clang'
)

# We set a different output_base so that caches do not interfere with each other.
bazel --output_base="$CACHE_DIR/clang" build "${bazel_build_flags[@]}" //oak/server/dev:oak
