#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "${SCRIPTS_DIR}/common"

while getopts "s:h" opt; do
  case "${opt}" in
    h)
      echo -e "Usage: ${0} [-s base|logless]

Build the specified version of the Oak Runtime server.

  -s    Server type:
          - base: base version of the server (default)
          - logless: base version of the server with debug logging compiled out
  -h    Print Help (this message) and exit"
      exit 0;;
    s)
      case "${OPTARG}" in
        base)
          ;;
        logless)
          cargo_build_flags+=("--no-default-features");;
        *)
          echo "Invalid server type: ${OPTARG}"
          exit 1;;
      esac;;
    *)
      echo "Invalid argument: ${OPTARG}"
      exit 1;;
  esac
done

readonly SERVER_BIN_DIR="${PWD}/oak/server/bin"
rm -rf "${SERVER_BIN_DIR:?}"
mkdir --parents "${SERVER_BIN_DIR}"
# `--out-dir` is unstable and requires `-Z unstable-options`.
cargo build "${cargo_build_flags[@]}" --manifest-path=oak/server/rust/oak_loader/Cargo.toml \
  --out-dir="${SERVER_BIN_DIR}" -Z unstable-options
