#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

bazel_build_flags+=(
    '--config=enc-sim'
)

bazel build "${bazel_build_flags[@]}" \
    "//oak/server/asylo:oak" \
    "//oak/server/asylo:oak_app" \
    "//oak/common:app_config_serializer"
