#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Run all examples.
for language in rust cpp; do
  examples="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/'"${language}"'$' | cut -d'/' -f2 | uniq)"
  for example in ${examples}; do
    "${SCRIPTS_DIR}/build_example" -l "${language}" -e "${example}"
  done
done
