#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

for example in hello_world aggregator; do
  "${SCRIPTS_DIR}/build_example_android" -e "${example}"
done
