#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

cd cargo || exit 1
# Remove existing raze-generated BUILD files before regenerating, so
# the files for removed/upgraded deps get cleared.
rm -f remote/*
cargo build
cargo raze
# `remote/ring-0.16.12.BUILD` contains manually added environment
# variables that were added to solve #890:
# https://github.com/project-oak/oak/issues/890#issuecomment-621773356
git checkout remote/ring-0.16.12.BUILD
