#!/bin/bash
#
# Check all Rust dependencies using cargo-deny.

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

for crate in "${ALL_CRATES[@]}"; do
  cargo deny --manifest-path="${crate}/Cargo.toml" check
done 
