#!/bin/bash
#
# Checks that source files have no naked TODOs.

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

check_todo() {
  local path="$1"
  local result
  result=$(grep --with-filename --line-number TODO "$path" | grep --invert-match --regexp='TODO(#[0-9][0-9]*)')
  if [[ -n $result ]]; then
    echo "$result"
    return 1
  fi
}

main() {
  if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <path>"
    exit 1
  fi

  local code=0
  while [[ $# -gt 0 ]]; do
    local path="$1"
    check_todo "$path" || code=1
    shift
  done
  exit $code
}

main "$@"
