#!/usr/bin/env bash

set -o errexit
set -o nounset

# Check shell scripts for common mistakes.
find scripts -type f -exec shellcheck {} +

# Run clang-format and rustfmt on the entire codebase to check if it's
# well formatted. Exit codes:
#  - 1 there are files to be formatted.
#  - 0 everything looks fine.
./third_party/run-clang-format/run-clang-format.py -r oak examples

# Fortunately, rustfmt has the --check option that will make it exit with 1
# if formatting has to be applied.
find examples rust -type f -name '*.rs' -exec rustfmt --check {} +

# Run clippy to lint the rust code
# First do the examples folder
(cd "$PWD/examples/" && cargo clippy)

# After this run it on all the subfolders in rust
# TODO: change this once we have a single workspace
find rust -type f -name 'Cargo.toml' -execdir cargo clippy \;
