#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# shellcheck source=scripts/gcp_common
source "$SCRIPTS_DIR/gcp_common"

# TODO(#1943): Remove when #1943 is submitted.
cargo build --target=x86_64-unknown-linux-musl --manifest-path=./oak_functions/loader/Cargo.toml --release

# Build and push base Oak Functions Loader image.

readonly FUNCTIONS_DOCKER_IMAGE_NAME='gcr.io/oak-ci/oak-functions'

docker build \
  --tag="${FUNCTIONS_DOCKER_IMAGE_NAME}:latest" \
  ./oak_functions

docker push "${FUNCTIONS_DOCKER_IMAGE_NAME}:latest"

# Build and push the `weather_lookup` example application built on Oak Functions.

cargo -Zunstable-options build --release \
  --target=wasm32-unknown-unknown \
  --manifest-path=./oak_functions/examples/weather_lookup/module/Cargo.toml \
  --out-dir=./oak_functions/examples/weather_lookup/bin

readonly FUNCTIONS_EXAMPLE_DOCKER_IMAGE_NAME='gcr.io/oak-ci/oak-functions-weather-lookup'

docker build \
  --tag="${FUNCTIONS_EXAMPLE_DOCKER_IMAGE_NAME}:latest" \
  ./oak_functions/examples/weather_lookup

docker push "${FUNCTIONS_EXAMPLE_DOCKER_IMAGE_NAME}:latest"

gcloud auth activate-service-account \
  --project="${GCP_PROJECT_ID}" \
  --key-file="${GCP_ACCOUNT_FILE}"

# Deploy the example application to Cloud Run.
#
# Keep at least one instance alive all the time, even if there is no traffic to serve, since it may
# take a while for it to start up.
#
# Use beta channel of Cloud Run in order to support HTTP2 until it is generally available.

gcloud beta run deploy "${FUNCTIONS_INSTANCE_NAME}" \
  --region="${GCP_REGION}" \
  --image="${FUNCTIONS_EXAMPLE_DOCKER_IMAGE_NAME}:latest" \
  --allow-unauthenticated \
  --use-http2 \
  --concurrency=20 \
  --memory=8G \
  --cpu=4 \
  --min-instances=1 \
  --max-instances=10 \
  --platform=managed

# Find the gateway URL.
readonly HOST_NAME="$(gcloud api-gateway gateways describe "${GATEWAY_ID}" --location="${GCP_REGION}" --format='value(defaultHostname)')"

#Build the client to test the connection.
cargo build --manifest-path=./oak_functions/client/Cargo.toml

# Attempt to communicate with the newly deployed application.
./oak_functions/client/target/debug/oak_functions_client \
  --uri="https://${HOST_NAME}" \
  --request='{"lat":52,"lon":0}'
