#!/bin/sh
set -e
set -x

docker build --tag=oak .
docker run \
  --interactive \
  --tty \
  --volume=bazel-cache:/root/.cache/bazel \
  --volume=$PWD:/opt/my-project \
  --workdir=/opt/my-project \
  --publish=8888:8888 \
  oak:latest \
  bash
