#!/usr/bin/env bash

# This script runs the provided command in the Docker container corresponding to the currently
# checked-in image id.

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# In order for the docker-cli inside the container to use the host dockerd,
# we need permissions for the user with the same gid as the host
if [[ "${OSTYPE}" == "darwin"*  ]]; then
  readonly HOST_DOCKER_GID="$(dscl . -read /Groups/staff | awk '($1 == "PrimaryGroupID:") { print $2 }')"
else
  readonly HOST_DOCKER_GID="$(getent group docker | cut -d: -f3)"
fi

mkdir -p './bazel-cache'
mkdir -p './cargo-cache'
mkdir -p './sccache-cache'

# Generate .env file to use with the docker image
source "$SCRIPTS_DIR/docker_create_env_file"

docker_run_flags=(
  '--rm'
  '--tty'
  # Use the generated .env file
  '--env-file=.docker.env'
  "--volume=$PWD/bazel-cache:/home/docker/.cache/bazel"
  "--volume=$PWD/cargo-cache:/home/docker/.cargo"
  "--volume=$PWD/sccache-cache:/home/docker/.cache/sccache"
  "--volume=$PWD:/workspace"
  '--volume=/dev/log:/dev/log'
  '--workdir=/workspace'
  '--network=host'
  # We need to use Docker from inside the container, but only for build.
  # To do that, we map the socket from the host and add the right group.
  '--volume=/var/run/docker.sock:/var/run/docker.sock'
  "--group-add=$HOST_DOCKER_GID"
)

# If the host supports KVM, allow the docker image to use it.
if [[ -e "/dev/kvm" ]]; then
  readonly HOST_KVM_GID="$(getent group kvm | cut -d: -f3)"
  docker_run_flags+=(
    "--device=/dev/kvm"
  )
fi

# If the host supports virtio vhost vsock, allow the docker image to use it.
if [[ -e "/dev/vhost-vsock" ]]; then
  docker_run_flags+=(
    "--device=/dev/vhost-vsock"
  )
fi

# If the host supports the vsock device, allow the docker image to use it.
if [[ -e "/dev/vsock" ]]; then
  docker_run_flags+=(
    "--device=/dev/vsock"
  )
fi

# Some CI systems (GitHub actions) do not run with an interactive TTY attached.
if [[ -z "${CI:-}" ]]; then
  docker_run_flags+=('--interactive')
fi

# Create a new user with a fixed name but with the same uid and gid as the host user, and use that
# user to run the provided command.
docker run "${docker_run_flags[@]}" "$DOCKER_IMAGE_ID" ./scripts/fix_docker_user_and_run "$*"
