#!/usr/bin/env bash

# This script can be used by anyone, including CI, to pull a version of the image from Google
# Container Registry, which should allow download public downloads.
# See https://pantheon.corp.google.com/gcr/settings?project=oak-ci&folder&organizationId=433637338589

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

docker pull "$DOCKER_IMAGE_NAME:latest"
