#!/bin/sh
set -e
set -x

docker build --tag=oak .
# The second --publish option below publishes a range of ports, of which the minimum value needs
# to match value of flag node_port_min, and the maximum the flag node_port_max (see
# oak/server/oak_manager.cc).
docker run \
  --interactive \
  --tty \
  --volume=$PWD/bazel-cache:/root/.cache/bazel \
  --volume=$PWD:/opt/my-project \
  --workdir=/opt/my-project \
  --publish=8888:8888 \
  --publish=7000-8000:7000-8000 \
  oak:latest \
  "$@"
