#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o xtrace

readonly OAK_REMOTE_CACHE_KEY='./.oak_remote_cache_key.json'

# Use the remote cache, assuming it is publicly readable.
# See https://pantheon.corp.google.com/storage/browser/oak-bazel-cache?project=oak-ci
bazel_build_flags=(
    '--remote_cache=https://storage.googleapis.com/oak-bazel-cache'
    '--config=fuzzer'
)
# If we now have a key file, use it, otherwise disable uploading artifacts to remote cache.
# Note that this is only needed to write to the cache, not to read from it.
if [[ -f "$OAK_REMOTE_CACHE_KEY" ]]; then
    bazel_build_flags+=(
        "--google_credentials=$OAK_REMOTE_CACHE_KEY"
    )
else
    bazel_build_flags+=(
        '--remote_upload_local_results=false'
    )
fi

bazel build "${bazel_build_flags[@]}" //oak/server:wasm_node_fuzz
./bazel-bin/oak/server/wasm_node_fuzz
