#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Use the remote cache, assuming it is publicly readable.
# See https://pantheon.corp.google.com/storage/browser/oak-bazel-cache?project=oak-ci
bazel_build_flags+=(
    '--config=fuzzer'
)

bazel build "${bazel_build_flags[@]}" //oak/server:wasm_node_fuzz
./bazel-bin/oak/server/wasm_node_fuzz
