#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Generates a compile_commands.json file at $(bazel info execution_root) for
# your Clang tooling needs.

readonly FILE_NAME="compile_commands.json"
readonly BAZEL_ROOT="$(bazel info execution_root)"
cd "$BAZEL_ROOT" || exit 1
echo '[' > "$FILE_NAME"
COUNT=0
find . -name '*.compile_command.json' -print0 | while read -r -d '' fname; do
  if ((COUNT++)); then
    echo ',' >> "$FILE_NAME"
  fi
  sed -e "s|@BAZEL_ROOT@|$BAZEL_ROOT|g" < "$fname" | \
  # Change GCC parameters to Clang.
  sed -e "s|-fno-canonical-system-headers|-no-canonical-prefixes|g" | \
  sed -e "s|-Wno-free-nonheap-object|-Wno-sequence-point|g" | \
  sed -e "s|-Wunused-but-set-parameter|-Wunused-parameter|g" >> "$FILE_NAME"
done
echo ']' >> "$FILE_NAME"

