#!/usr/bin/env bash


readonly BASH_COMPLETION_DIR="$(realpath ".")"
readonly BASH_COMPLETION_FILE=$BASH_COMPLETION_DIR/.runner_bash_completion 

./scripts/runner completion --out-dir="$BASH_COMPLETION_DIR"

echo "
Wrote the bash completion file for runner to ${BASH_COMPLETION_FILE}
Please source this file in your .bashrc, e.g., through
  
echo \"
#activate runner auto-complete
if [ -f ${BASH_COMPLETION_FILE} ]; then
  source ${BASH_COMPLETION_FILE}
fi\" >> ~/.bashrc
"
