#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# shellcheck source=scripts/gcp_common
source "$SCRIPTS_DIR/gcp_common"

cargo run --manifest-path=./oak_functions/lookup_data_generator/Cargo.toml -- \
  --out-file-path=/tmp/lookup_data_weather_sparse_s2 \
  weather-sparse

# Once uploaded, this file is publicly available at the following URL:
# https://storage.googleapis.com/oak_lookup_data/lookup_data_weather_sparse_s2
gsutil cp /tmp/lookup_data_weather_sparse_s2 gs://oak_lookup_data/lookup_data_weather_sparse_s2
