#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Changed files that are tracked by git.
readonly GIT_STATUS=$(git status --short)
# Changed files that are untracked/ignored by git.
readonly GIT_CLEAN_STATUS=$(git clean --dry-run -x -d)

if [[ "$GIT_STATUS" || "$GIT_CLEAN_STATUS" ]]; then
    echo 'Please re-run this script from a clean commit.'
    "$GIT_STATUS" && echo "The following tracked changes were present: $GIT_STATUS"
    "$GIT_CLEAN_STATUS" && echo "The following untracked changes were present: $GIT_CLEAN_STATUS"

    exit 1
fi
