#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Prints the MRENCLAVE value of the unsigned enclave code.
bazel build --config=sgx-sim //oak/server/asylo:oak_mrenclave
cat bazel-bin/oak/server/asylo/oak_mrenclave.txt
