#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

./scripts/runner \
  --commands \
  build-functions-server \
  --server-variant=base

# If the release was built from the latest upstream commit, then this hash should match that from
# https://github.com/project-oak/oak/blob/hashes/reproducibility_index.
sha256sum ./target/x86_64-unknown-linux-musl/release/oak_functions_loader_base
