#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# For each Rust workspace, run tests, then run doc tests, then run clippy
# (turning warnings into errors).
#
# See:
# - https://doc.rust-lang.org/cargo/commands/cargo-test.html
# - https://github.com/rust-lang/rust-clippy.

export RUST_BACKTRACE=1

cargo test --all-targets
cargo test --doc
cargo clippy --all-targets -- --deny=warnings

bazel_build_flags+=(
  '--keep_going'
)

bazel build "${bazel_build_flags[@]}" -- //oak/...:all

bazel test "${bazel_build_flags[@]}" -- //oak/...:all
