#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Generate compilation database.
./scripts/build_server_asylo -c
./scripts/build_server_dev -c
#./scripts/build_examples -c
bazel build \
    --experimental_action_listener=@io_kythe//kythe/cxx/tools/generate_compile_commands:extract_json \
    //oak/client:manager_client //oak/client:application_client
./third_party/kythe/generate_compilation_database.sh

# Run clang-tidy.
#SOURCE_FILES=$(find . )
#clang-tidy -p "$(bazel info execution_root)" "$SOURCE_FILES"