#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

readonly GRPC_PORT="${GRPC_PORT:-8888}"

"$SCRIPTS_DIR/build_server_asylo"
./bazel-bin/oak/server/asylo/oak --grpc_port="${GRPC_PORT}"
