#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

"$SCRIPTS_DIR/build_server_dev"

# Launching the server requires a `--application=<dir>/config.bin` flag.
# We use a different symlink prefix for clang-based artifacts.
./bazel-clang-bin/oak/server/dev/dev_oak_runner "$@"
