#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Build Oak server.
"$SCRIPTS_DIR/build_server_dev" "$@"

# Run Oak server and ensure it is killed on exit.
./bazel-clang-bin/oak/server/dev/oak &
readonly server_pid=$!
to_kill+=("${server_pid}")

# Run Rust-based Oak examples, re-using the same Oak server instance.
readonly RUST_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module/rust$' | cut -d'/' -f2)"
for example in ${RUST_EXAMPLES}; do
  deps_pid=""
  deps_cmd=$(cat "./examples/${example}/run_deps" || true)
  if [ -n "${deps_cmd}" ]; then
    # Run the dependencies of the example.
    ${deps_cmd} &
    deps_pid=$!
  fi

  "${SCRIPTS_DIR}/run_example" "${example}"

  if [ -n "${deps_pid}" ]; then
    kill_pid "${deps_pid}"
  fi
done

# Run C++-based Oak examples.
readonly CPP_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module/cpp$' | cut -d'/' -f2)"
for example in ${CPP_EXAMPLES}; do
  "${SCRIPTS_DIR}/run_example" -c "${example}"
done
