#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Build Oak server.
"$SCRIPTS_DIR/build_server_asylo"

# Run Rust-based Oak examples, each with their own Oak server instance.
# Note that the chat example cannot be run because the client is interactive.
# TODO(#462): Re-enable chat example, even if it may be just loading the server-side code and not
# interact with it.
readonly RUST_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/rust$' | cut -d'/' -f2 | uniq | grep -v chat)"

for example in ${RUST_EXAMPLES}; do
  ./bazel-bin/oak/server/asylo/oak &
  SERVER_PID=$!
  "${SCRIPTS_DIR}/run_example" "${example}"
  # TODO: Ensure that background processes are killed with something like `trap cleanup_fn EXIT`.
  kill -s SIGTERM "$SERVER_PID"
done

# Run C++-based Oak examples.
# TODO: Run TensorFlow example when Emscripten imports will be fixed.
# https://github.com/project-oak/oak/issues/439
readonly CPP_EXAMPLES="$(find examples -mindepth 2 -maxdepth 4 -type d -regex '.*/module.*/cpp$' | cut -d'/' -f2 | uniq | grep -v tensorflow)"
for example in ${CPP_EXAMPLES}; do
  ./bazel-bin/oak/server/asylo/oak &
  SERVER_PID=$!
  "${SCRIPTS_DIR}/run_example" "${example}"
  kill -s SIGTERM "$SERVER_PID"
done
