#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

IS_CPP=false

while getopts ":hcC" opt; do
    case "$opt" in
    h)
        echo -e "Usage: $0 [-c] [-h] [-C opts] example_name
  -c    Run the C++ version of the example
  -h    Print this message
  -C    Pass subsequent options to example client"
        exit 0
        ;;
    c)
        echo "Running Node in C++ mode"
        IS_CPP=true
        ;;
    C)
        echo "Passing remaining arguments to client"
        break
        ;;
    \?)
        echo "Invalid option -${OPTARG}"
        exit 1
        ;;
    esac
done
shift $((OPTIND -1))

readonly NAME="${*: -1}"
if [[ -z "$NAME" ]]; then
  echo "Missing example name, use -h for help"
  exit 1
fi

readonly CLIENT_ARGS=("${@:1:$((${#@}-1))}")

readonly OAK_MANAGER_ADDRESS="${OAK_MANAGER_ADDRESS:-127.0.0.1:8888}"

"$SCRIPTS_DIR/build_example" "$NAME"

if [ "$IS_CPP" = true ]; then
  readonly MODULE_PATH="./bazel-wasm-bin/examples/$NAME/module/cpp"
else
  readonly MODULE_PATH="./examples/target/wasm32-unknown-unknown/release"
fi
# Accumulate all modules in a comma-separated list, in alphabetical order.
readonly MODULES=$(find "$MODULE_PATH/$NAME"*.wasm | tr '\n' ',' | sed 's/,$//')

"./bazel-client-bin/examples/$NAME/client/client" \
  --manager_address="$OAK_MANAGER_ADDRESS" \
  --module="$MODULES" \
  "${CLIENT_ARGS[@]}"
