#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# For each Rust workspace, run tests, then run doc tests, then run clippy
# (turning warnings into errors).
#
# See:
# - https://doc.rust-lang.org/cargo/commands/cargo-test.html
# - https://github.com/rust-lang/rust-clippy.

export RUST_BACKTRACE=1

cargo test --all-targets
cargo test --doc
cargo clippy --all-targets -- --deny=warnings

bazel_build_flags+=(
  '--keep_going'
)

# Check everything builds (except Asylo-specific targets).
bazel build "${bazel_build_flags[@]}" -- //oak/...:all -//oak/server/asylo:all

# Run tests that are suitable for running on the host system (rather than the target).
bazel test "${bazel_build_flags[@]}" \
  //oak/server:host_tests \
  //oak/server/storage:host_tests \
  //oak/server/time:host_tests \
  //oak/common:host_tests
