#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

# Build the example client and Application in coverage mode and run them.
"${SCRIPTS_DIR}/runner" run-examples --example-name=abitest --coverage

# Generate coverage summary
(
    cd oak/server || exit 1
    grcov ./target/debug/ \
          --source-dir=. \
          --llvm \
          --branch \
          --ignore-not-existing \
          --excl-line="(panic!|unreachable!|#\\[derive\\()" \
          --excl-start=LCOV_EXCL_START \
          --excl-stop=LCOV_EXCL_STOP \
          --output-type=lcov \
          --output-path=./target/debug/lcov.info
)
