#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

while getopts ":hC" opt; do
    case "$opt" in
    h)
        echo -e "Usage: $0 [-c] [-h] [-C opts] example_name
  -h    Print this message
  -C    Pass subsequent options to example client"
        exit 0
        ;;
    C)
        echo "Passing remaining arguments to client"
        break
        ;;
    \?)
        echo "Invalid option -${OPTARG}"
        exit 1
        ;;
    esac
done
shift $((OPTIND -1))

readonly NAME="${*: -1}"
if [[ -z "$NAME" ]]; then
  echo "Missing example name, use -h for help"
  exit 1
fi

readonly CLIENT_ARGS=("${@:1:$((${#@}-1))}")

readonly OAK_APPLICATION_ADDRESS="${OAK_APPLICATION_ADDRESS:-127.0.0.1:8080}"

"$SCRIPTS_DIR/build_example" "$NAME"

"./bazel-client-bin/examples/$NAME/client/client" \
  --address="$OAK_APPLICATION_ADDRESS" \
  "${CLIENT_ARGS[@]}"
