#!/usr/bin/env bash

set -o errexit
set -o nounset

readonly DOCKER_UID="${UID:-0}"
readonly DOCKER_GID="${GID:-0}"
readonly DOCKER_USER="${USER:-root}"

readonly SCRIPTS_DIR="$(dirname "$0")"

# Run Oak server.
"$SCRIPTS_DIR/build_server_docker"
readonly SERVER_CONTAINER_ID=$("$SCRIPTS_DIR/docker_run" \
  --detach \
  ./bazel-bin/oak/server/oak)

# Run Oak examples.
find examples -type f -name run -exec "$SCRIPTS_DIR/docker_run" {} \;

docker stop "$SERVER_CONTAINER_ID"

