#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

"$SCRIPTS_DIR/build_server_asylo"

# Launching the server requires a `--application=<dir>/config.bin` flag.
./bazel-bin/oak/server/asylo/asylo_oak_runner "$@"
