#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

sccache --show-stats
cargo run --manifest-path="${SCRIPTS_DIR}/../runner/Cargo.toml" -- "$@"
sccache --show-stats
