#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

cargo run --target=x86_64-unknown-linux-musl --manifest-path="${SCRIPTS_DIR}/../xtask/Cargo.toml" -- "$@"
