#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

cargo run --manifest-path="${SCRIPTS_DIR}/../xtask/Cargo.toml" -- "$@"

if [[ -n "${CI:-}" ]]; then
  sccache --show-stats
fi
