#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o xtrace
set -o pipefail

export PROJECT=oak-ci
export DOCKER_IMAGE=europe-docker.pkg.dev/$PROJECT/trusted-shuffler/trusted-shuffler-server:latest

cargo build \
    --manifest-path=experimental/trusted_shuffler/server/Cargo.toml \
    --target=x86_64-unknown-linux-musl \
    --release
cp -f \
    ./target/x86_64-unknown-linux-musl/release/trusted_shuffler_server \
    ./experimental/trusted_shuffler/bin/trusted_shuffler_server
docker build \
    --tag=$DOCKER_IMAGE \
    ./experimental/trusted_shuffler
