#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"

readonly ROUNDS=20 
readonly LOG_LEVEL=error
# ROUNDS * QPS has to be a multiple of K

KS=(500 1000 2000)
QPSS=$(seq 100 100 1000)

cargo build --manifest-path=experimental/trusted_shuffler/server/Cargo.toml
cargo build --manifest-path=experimental/trusted_shuffler/backend/Cargo.toml
cargo build --manifest-path=experimental/trusted_shuffler/client/Cargo.toml

# Write into file.
echo "k,qps,rounds,actual_time,delay_in_ms" > data.csv

for K in $KS
do
  for QPS in $QPSS
  do
    # Echo progress.
    echo "Starting: $K, $QPS"

    RUST_LOG=$LOG_LEVEL cargo run --manifest-path=experimental/trusted_shuffler/server/Cargo.toml -- \
      --k=${K} --listen-address="[::]:8080" --backend-url="http://localhost:8888" &
    sleep 1
    SERVER_PID=$!

    RUST_LOG=$LOG_LEVEL cargo run --manifest-path=experimental/trusted_shuffler/backend/Cargo.toml -- \
      --listen-address="[::]:8888" &
    sleep 1
    BACKEND_PID=$!

    CLIENT_OUTPUT=$(RUST_LOG=$LOG_LEVEL cargo run --manifest-path=experimental/trusted_shuffler/client/Cargo.toml -- \
     --server-url="http://localhost:8080" --qps=${QPS} --rounds=${ROUNDS})

    echo "${K},${QPS},${ROUNDS},${CLIENT_OUTPUT}" >> data.csv 

    kill -9 "${SERVER_PID}"
    kill -9 "${BACKEND_PID}"
  done 
done