#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"

readonly K=10
readonly QPS=40
readonly ROUNDS=3

cargo build --manifest-path=experimental/trusted_shuffler/server/Cargo.toml
cargo build --manifest-path=experimental/trusted_shuffler/backend/Cargo.toml
cargo build --manifest-path=experimental/trusted_shuffler/client/Cargo.toml

RUST_LOG=info cargo run --manifest-path=experimental/trusted_shuffler/server/Cargo.toml -- \
  --k=${K} --listen-address="[::]:8080" --backend-url="http://localhost:8888" &
sleep 1
readonly SERVER_PID=$!

RUST_LOG=info cargo run --manifest-path=experimental/trusted_shuffler/backend/Cargo.toml -- \
  --listen-address="[::]:8888" &
sleep 1
readonly BACKEND_PID=$!

RUST_LOG=info cargo run --manifest-path=experimental/trusted_shuffler/client/Cargo.toml -- \
  --server-url="http://localhost:8080" --qps=${QPS} --rounds=${ROUNDS}

echo "k=${K}, qps=${QPS}, rounds=${ROUNDS}"

kill -9 "${SERVER_PID}"
kill -9 "${BACKEND_PID}"
