#!/bin/bash
#
# Build browser introspection client.

# TODO(#913): Implement introspection client

readonly DIR=./dist
mkdir -p $DIR

readonly INDEXJS=$DIR/index.js
readonly INDEXHTML=$DIR/index.html

if [[ ! -f $INDEXJS ]]
then
  touch $INDEXJS
fi

if [[ ! -f $INDEXHTML ]]
then
  touch $INDEXHTML
fi
