(function() {var implementors = {};
implementors["oak_runtime"] = [{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.ApplicationConfiguration.html\" title=\"struct oak_runtime::proto::manager::ApplicationConfiguration\">ApplicationConfiguration</a>",synthetic:false,types:["oak_runtime::proto::manager::ApplicationConfiguration"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.NodeConfiguration.html\" title=\"struct oak_runtime::proto::manager::NodeConfiguration\">NodeConfiguration</a>",synthetic:false,types:["oak_runtime::proto::manager::NodeConfiguration"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.WebAssemblyConfiguration.html\" title=\"struct oak_runtime::proto::manager::WebAssemblyConfiguration\">WebAssemblyConfiguration</a>",synthetic:false,types:["oak_runtime::proto::manager::WebAssemblyConfiguration"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.LogConfiguration.html\" title=\"struct oak_runtime::proto::manager::LogConfiguration\">LogConfiguration</a>",synthetic:false,types:["oak_runtime::proto::manager::LogConfiguration"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.StorageProxyConfiguration.html\" title=\"struct oak_runtime::proto::manager::StorageProxyConfiguration\">StorageProxyConfiguration</a>",synthetic:false,types:["oak_runtime::proto::manager::StorageProxyConfiguration"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.CreateApplicationRequest.html\" title=\"struct oak_runtime::proto::manager::CreateApplicationRequest\">CreateApplicationRequest</a>",synthetic:false,types:["oak_runtime::proto::manager::CreateApplicationRequest"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.CreateApplicationResponse.html\" title=\"struct oak_runtime::proto::manager::CreateApplicationResponse\">CreateApplicationResponse</a>",synthetic:false,types:["oak_runtime::proto::manager::CreateApplicationResponse"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.TerminateApplicationRequest.html\" title=\"struct oak_runtime::proto::manager::TerminateApplicationRequest\">TerminateApplicationRequest</a>",synthetic:false,types:["oak_runtime::proto::manager::TerminateApplicationRequest"]},{text:"impl Message for <a class=\"struct\" href=\"oak_runtime/proto/manager/struct.TerminateApplicationResponse.html\" title=\"struct oak_runtime::proto::manager::TerminateApplicationResponse\">TerminateApplicationResponse</a>",synthetic:false,types:["oak_runtime::proto::manager::TerminateApplicationResponse"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
