#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

for file in "$@"; do
    if ! head -n 50 "$file" | grep "Apache License" > /dev/null
    then
        echo "ERROR: Missing Apache License in $file"
        exit 1
    fi
done
