#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Run bazel mod deps on each provided MODULE.bazel file to ensure that the lock file is fully up to date.
for file in "$@"; do
  echo "Running bazel mod deps for ${file}"
  pushd "$(dirname "${file}")"
  if ! bazel info workspace; then
    echo "Skipping bazel mod deps for $(pwd) since it is not a root module."
    popd
    continue
  fi

  # Only check up-to-dateness, don't try to fix, so that this runs reasonably fast.
  if ! bazel mod deps --lockfile_mode=error; then
    printf "Bazel lockfiles are out of date, run:\n\njust bazel-lockfile-all\n"
    exit 1
  fi

  popd
done
