#!/usr/bin/env bash
# shellcheck disable=SC2034  
# Unused variables OK as this script is `source`d.

set -o errexit
set -o nounset
set -o xtrace
set -o pipefail

readonly PROJECT='oak-ci'
readonly DOCKER_IMAGE="gcr.io/${PROJECT}/trusted-shuffler:latest"
readonly DEPLOYMENT='trusted-shuffler'
