#!/usr/bin/env bash

# A simple script to create a tarball of an example OCI Runtime Bundle (https://github.com/opencontainers/runtime-spec/blob/4e3b9264a330d094b0386c3703c5f379119711e8/bundle.md)
# that can be executed on Oak Containers. Used for manual testing during
# development. Down the line we probably want to replace this.

rm -rf ./temp_out
mkdir -p ./temp_out
docker build --tag="oak_container_example" .
docker export --output="./temp_out/oak_container_example_rootfs.tar" $(docker create oak_container_example)
mkdir -p ./temp_out/rootfs
tar -xf ./temp_out/oak_container_example_rootfs.tar -C ./temp_out/rootfs
rm ./temp_out/oak_container_example_rootfs.tar
cp config.json ./temp_out/config.json
tar -cvf oak_container_example_bundle.tar -C ./temp_out .
rm -rf ./temp_out
