#!/usr/bin/env bash

# A simple script to create a tarball of an example OCI Runtime Bundle (https://github.com/opencontainers/runtime-spec/blob/4e3b9264a330d094b0386c3703c5f379119711e8/bundle.md)
# that can be executed on Oak Containers. Used for manual testing during
# development. Down the line we probably want to replace this.

rm -rf ./target
mkdir -p ./target
cargo build --package="oak_containers_example_trusted_application" -Z unstable-options --out-dir="./target/"
docker build --tag="oak_container_example" .
mkdir -p ./target/oci_filesystem_bundle
docker export --output="./target/oak_container_example_rootfs.tar" "$(docker create oak_container_example)"
mkdir -p ./target/oci_filesystem_bundle/rootfs
tar -xf ./target/oak_container_example_rootfs.tar -C ./target/oci_filesystem_bundle/rootfs
cp ./config.json ./target/oci_filesystem_bundle
tar -cvf ./target/oak_container_example_oci_filesystem_bundle.tar -C ./target/oci_filesystem_bundle .

