/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_oak_crypto_hpke_Context_SenderRequestContext */

#ifndef _Included_com_google_oak_crypto_hpke_Context_SenderRequestContext
#define _Included_com_google_oak_crypto_hpke_Context_SenderRequestContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_oak_crypto_hpke_Context_SenderRequestContext
 * Method:    nativeSeal
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_oak_crypto_hpke_Context_00024SenderRequestContext_nativeSeal
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_google_oak_crypto_hpke_Context_SenderRequestContext
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_oak_crypto_hpke_Context_00024SenderRequestContext_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
