#!/bin/sh
set -e
set -x

cargo build --release --target=wasm32-unknown-unknown --manifest-path=examples/private_set_intersection/Cargo.toml
bazel run //examples/private_set_intersection/client -- \
  --module=$PWD/examples/target/wasm32-unknown-unknown/release/private_set_intersection.wasm
