#!/bin/bash
#
# Build browser introspection client.

# Install npm modules if needed
readonly CURRENT_PACKAGE_LOCK="./package-lock.json"
readonly LAST_INSTALLED_PACKAGE_LOCK="./node_modules/.cache/last-install-package-lock.json"
if ! cmp --silent "$CURRENT_PACKAGE_LOCK" "$LAST_INSTALLED_PACKAGE_LOCK"; then
  npm ci
fi

# Generate JavaScript code from the introspection_events proto
mkdir -p ./protoc_out
readonly PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
readonly PROTO_OUT_DIR="./protoc_out"
protoc \
    --proto_path=../../ \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --js_out="import_style=commonjs,binary:${PROTO_OUT_DIR}" \
    --ts_out="${PROTO_OUT_DIR}" \
    ../../proto/introspection_events.proto \
    ../../oak_abi/proto/label.proto

# Build JavaScript bundle
npx webpack --env.NODE_ENV=production
