#!/bin/bash
#
# Removes the stale ./node_modules/.cache/last-install-package-lock.json after
# an NPM package has been added or removed. This additional hook is needed since
# that file can only be genereated after dependencies are installed as whole,
# but not when individual dependencies are added or removed.

# Check if this hooks was called from a dependency, not from the source package.
if [[ $INIT_CWD != $PATH ]]; then
  cd $INIT_CWD
  rm -rf ./node_modules/.cache/last-install-package-lock.json
fi
