#!/bin/bash
#
# Maintains a copy representing the package-lock.json at the time of the
# last NPM install in ./node_modules/.cache/last-install-package-lock.json.
# Doing this permits the build script to skip npm installs on subsequent runs
# if dependencies did not change.

# Setup hook to run on subsequent additions and removals of dependencies.
# Ref: https://docs.npmjs.com/misc/scripts#hook-scripts
if [[ ! -d "./node_modules/.hooks/postinstall" || ! -d "./node_modules/.hooks/postuninstall" ]]; then
  mkdir -p ./node_modules/.hooks/
  cp ./npm_hook_package_added_or_removed ./node_modules/.hooks/postinstall
  cp ./npm_hook_package_added_or_removed ./node_modules/.hooks/postuninstall
fi

# Copy the package-lock.json at the time of install
mkdir -p ./node_modules/.cache/
cp -rf ./package-lock.json ./node_modules/.cache/last-install-package-lock.json
