#!/bin/sh
set -e
set -x

OAK_MANAGER_ADDRESS=${OAK_MANAGER_ADDRESS:-127.0.0.1:8888}

cargo build --release --target=wasm32-unknown-unknown --manifest-path=examples/running_average/Cargo.toml
bazel run //examples/running_average/client \
  ${BAZEL_OPTS:+ "${BAZEL_OPTS}"} \
  -- \
  --manager_address="${OAK_MANAGER_ADDRESS}" \
  --module=$PWD/examples/target/wasm32-unknown-unknown/release/running_average.wasm
