// Copyright 2026 The Project Oak Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! # Future Work
//!
//! - TODO: b/486216666 - Replace `NoOpSessionBinder` with real
//!   `InstanceSessionBinder` once we create our own indirect binder.

use std::sync::Arc;

use oak_attestation_types::{attester::Attester, endorser::Endorser};
use oak_proto_rust::oak::attestation::v1::{Endorsements, Evidence};
use oak_session::{
    attestation::AttestationType, config::SessionConfig, handshake::HandshakeType,
    session_binding::SessionBinder,
};
use oak_session_endorsed_evidence::EndorsedEvidenceBindableAssertionGenerator;

const ATTESTATION_ID: &str = "oak-private-memory";

/// Creates a server-side `SessionConfig` using real DICE chain evidence from
/// the Oak orchestrator.
/// TODO: b/486216666 - Should be `InstanceSessionBinder` once we create our
/// own indirect binder. Currently a `NoOpSessionBinder` is passed.
pub fn orchestrator_session_config(
    evidence: Arc<Evidence>,
    endorsements: Arc<Endorsements>,
    session_binder: Box<dyn SessionBinder>,
) -> SessionConfig {
    let assertion_generator = Box::new(EndorsedEvidenceBindableAssertionGenerator::new(
        Arc::new(PrebuiltAttester { evidence }),
        Arc::new(PrebuiltEndorser { endorsements }),
        Arc::from(session_binder),
    ));
    SessionConfig::builder(AttestationType::SelfUnidirectional, HandshakeType::NoiseNN)
        .add_self_assertion_generator(ATTESTATION_ID.to_string(), assertion_generator)
        .build()
}

/// An [`Attester`] that returns pre-fetched [`Evidence`].
///
/// Used when the evidence has already been generated by the Oak orchestrator
/// and simply needs to be handed to the session framework.
struct PrebuiltAttester {
    evidence: Arc<Evidence>,
}

impl Attester for PrebuiltAttester {
    fn extend(&mut self, _encoded_event: &[u8]) -> anyhow::Result<()> {
        anyhow::bail!("PrebuiltAttester does not support extending evidence")
    }

    fn quote(&self) -> anyhow::Result<Evidence> {
        Ok((*self.evidence).clone())
    }
}

/// An [`Endorser`] that returns pre-fetched [`Endorsements`].
///
/// Used when the endorsements have already been generated by the Oak
/// orchestrator and simply need to be handed to the session framework.
struct PrebuiltEndorser {
    endorsements: Arc<Endorsements>,
}

impl Endorser for PrebuiltEndorser {
    fn endorse(&self, _evidence: Option<&Evidence>) -> anyhow::Result<Endorsements> {
        Ok((*self.endorsements).clone())
    }
}

/// A no-op [`SessionBinder`] that returns an empty binding.
///
/// TODO: b/486216666 - Replace with real `InstanceSessionBinder` once we
/// create our own indirect binder.
pub struct NoOpSessionBinder;

impl SessionBinder for NoOpSessionBinder {
    fn bind(&self, _bound_data: &[u8]) -> Vec<u8> {
        Vec::new()
    }
}
