// Copyright 2026 The Project Oak Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Production attestation configuration.

use std::sync::Arc;

use oak_attestation_types::{attester::Attester, endorser::Endorser};
use oak_proto_rust::oak::attestation::v1::{Endorsements, Evidence};
use oak_session::{
    attestation::AttestationType, config::SessionConfig, handshake::HandshakeType,
    session_binding::SessionBinder,
};
use oak_session_endorsed_evidence::EndorsedEvidenceBindableAssertionGenerator;

const ATTESTATION_ID: &str = "oak-private-memory";

/// Creates a server-side `SessionConfig` using real DICE chain evidence from
/// the Oak orchestrator.
pub fn orchestrator_session_config(
    attester: Arc<dyn Attester>,
    endorser: Arc<dyn Endorser>,
    session_binder: Arc<dyn SessionBinder>,
) -> SessionConfig {
    let assertion_generator = Box::new(EndorsedEvidenceBindableAssertionGenerator::new(
        attester,
        endorser,
        session_binder,
    ));
    SessionConfig::builder(AttestationType::SelfUnidirectional, HandshakeType::NoiseNN)
        .add_self_assertion_generator(ATTESTATION_ID.to_string(), assertion_generator)
        .build()
}

/// Creates a factory that produces server-side `SessionConfig`s.
///
/// This helper takes ownership of the evidence, endorsements, and session
/// binder, wraps them in `Arc`s, and returns a factory closure.
pub fn create_orchestrator_session_config_factory(
    evidence: Evidence,
    endorsements: Endorsements,
    session_binder: impl SessionBinder + 'static,
) -> Arc<dyn Fn() -> SessionConfig + Send + Sync> {
    let attester: Arc<dyn Attester> = Arc::new(PrebuiltAttester { evidence: Arc::new(evidence) });
    let endorser: Arc<dyn Endorser> =
        Arc::new(PrebuiltEndorser { endorsements: Arc::new(endorsements) });
    let session_binder: Arc<dyn SessionBinder> = Arc::new(session_binder);
    Arc::new(move || {
        orchestrator_session_config(attester.clone(), endorser.clone(), session_binder.clone())
    })
}

/// An [`Attester`] that returns pre-fetched [`Evidence`].
///
/// Used when the evidence has already been generated by the Oak orchestrator
/// and simply needs to be handed to the session framework.
struct PrebuiltAttester {
    evidence: Arc<Evidence>,
}

impl Attester for PrebuiltAttester {
    fn extend(&mut self, _encoded_event: &[u8]) -> anyhow::Result<()> {
        anyhow::bail!("PrebuiltAttester does not support extending evidence")
    }

    fn quote(&self) -> anyhow::Result<Evidence> {
        Ok((*self.evidence).clone())
    }
}

/// An [`Endorser`] that returns pre-fetched [`Endorsements`].
///
/// Used when the endorsements have already been generated by the Oak
/// orchestrator and simply need to be handed to the session framework.
struct PrebuiltEndorser {
    endorsements: Arc<Endorsements>,
}

impl Endorser for PrebuiltEndorser {
    fn endorse(&self, _evidence: Option<&Evidence>) -> anyhow::Result<Endorsements> {
        Ok((*self.endorsements).clone())
    }
}
